---
# Workflow which runs all Jupyter notebooks of the documentation and fails on errors.
# Copied from probnum: https://github.com/probabilistic-numerics/probnum
name: Jupyter Notebooks
on:
  # Triggers the workflow on push or pull request
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run_notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]
      - name: Execute all notebooks with nbconvert
        run: |-
          for file in $(find -wholename "./docs/source/notebooks/getting_started/*.ipynb" -not -path "**/.ipynb_checkpoints/*")
          do
              jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=python3 $file
          done
