name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Upgrade pip
      run: |
        pip install --upgrade pip
    - name: Build and install package
      run: |
        pip install .[ci]
    - name: Lint through tox
      run: |
        tox -e lint
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Upgrade pip
      run: |
        pip install --upgrade pip
    - name: Build and install package
      run: |
        pip install .[ci]
    - name: Build documentation with sphinx through tox
      run: |
        sudo apt-get install pandoc
        tox -e docs
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Upgrade pip
      run: |
        pip install --upgrade pip
    - name: Build and install package
      run: |
        pip install .[ci]
    - name: Run tests with pytest through tox
      run: |
        tox -e pytest
  byexample:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Upgrade pip
      run: |
        pip install --upgrade pip
    - name: Build and install package
      run: |
        pip install .[ci]
    - name: Run example snippets with byexample through tox
      run: |
        tox -e byexample
